/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package debezium.payload.header.transformer;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
